# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mailer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmailer.proto\x12\x06mailer\"\x0c\n\nVersionReq\"\x0c\n\nVersionRes2=\n\x06Mailer\x12\x33\n\x07Version\x12\x12.mailer.VersionReq\x1a\x12.mailer.VersionRes\"\x00\x42\x0eZ\x0cmailer/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mailer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014mailer/proto'
  _globals['_VERSIONREQ']._serialized_start=24
  _globals['_VERSIONREQ']._serialized_end=36
  _globals['_VERSIONRES']._serialized_start=38
  _globals['_VERSIONRES']._serialized_end=50
  _globals['_MAILER']._serialized_start=52
  _globals['_MAILER']._serialized_end=113
# @@protoc_insertion_point(module_scope)
