version: "3.8"
services:
  mysql:
    image: mysql
    container_name: microbooking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_HOST: '${DATABASE_HOST}'
      MYSQL_TCP_PORT: '${DATABASE_PORT}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DATABASE_USERNAME}", "-p${DATABASE_PASSWORD}", "-h${DATABASE_HOST}", "-P${DATABASE_PORT}", "ping"]
      retries: 3
      timeout: 5s
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      app:
        ipv4_address: 10.15.0.3
networks:
  app:
    name: microbooking-app
    driver: bridge
    ipam:
      config:
        - subnet: 10.15.0.0/16
          gateway: 10.15.0.1
volumes:
  database:
    name: microbooking-database
    driver: local
    driver_opts:
      type: none
      device: ./.docker-volumes/database
      o: bind
